const ASSET_BASE_PATH = '/minigames-assets';
const ASSET_VERSION = 'minigames-img-20260710b';

const encodeAssetPath = (assetPath) => String(assetPath).split('/').map(encodeURIComponent).join('/');
const withAssetVersion = (url) => `${url}?v=${ASSET_VERSION}`;

const makeDefinition = ({
  id,
  title,
  legacyName,
  moduleKey,
  section,
  coverAsset,
  description,
  difficultyAware = true,
  supportsPowerups = true,
  shapeMode = 'fixed',
  hudSchema = [],
  viewFlags = [],
  implemented = true,
}) => ({
  id,
  title,
  legacyName,
  moduleKey,
  section,
  coverAsset,
  description,
  difficultyAware,
  supportsPowerups,
  shapeMode,
  hudSchema,
  viewFlags,
  implemented,
  coverUrl: withAssetVersion(`${ASSET_BASE_PATH}/${encodeAssetPath(coverAsset.includes('/') ? coverAsset : `covers/${coverAsset}`)}`),
});

export const MINIGAME_REGISTRY = [
  makeDefinition({
    id: 'design-master-1',
    title: 'Design Master1',
    legacyName: 'Design Master1',
    moduleKey: 'design_master',
    section: 'Classic Challenges',
    coverAsset: 'Design Master1.png',
    description: 'Match an exact target pattern on the board.',
    hudSchema: ['patternText'],
    viewFlags: ['smallLabels'],
  }),
  makeDefinition({
    id: 'mystery-merge-1',
    title: 'Mystery Merge1',
    legacyName: 'Mystery Merge1',
    moduleKey: 'mystery_merge',
    section: 'Classic Challenges',
    coverAsset: 'Mystery Merge1.png',
    description: 'Most tiles are concealed until key moments.',
    viewFlags: ['hiddenMask', 'tileTextOverride'],
    hudSchema: ['actionButton'],
  }),
  makeDefinition({
    id: 'column-chaos',
    title: 'Column Chaos',
    legacyName: 'Column Chaos',
    moduleKey: 'column_chaos',
    section: 'Classic Challenges',
    coverAsset: 'Column Chaos.png',
    description: 'Survive random column swaps while building your score.',
    hudSchema: ['remainingSteps'],
  }),
  makeDefinition({
    id: 'gravity-twist-1',
    title: 'Gravity Twist1',
    legacyName: 'Gravity Twist1',
    moduleKey: 'gravity_twist',
    section: 'Classic Challenges',
    coverAsset: 'Gravity Twist1.png',
    description: 'Tiles keep falling under a strange gravity field.',
  }),
  makeDefinition({
    id: 'blitzkrieg',
    title: 'Blitzkrieg',
    legacyName: 'Blitzkrieg',
    moduleKey: 'blitzkrieg',
    section: 'Classic Challenges',
    coverAsset: 'Blitzkrieg.png',
    description: 'Race the countdown and chain high-value merges for bonus time.',
    hudSchema: ['countdown'],
  }),
  makeDefinition({
    id: 'tricky-tiles',
    title: 'Tricky Tiles',
    legacyName: 'Tricky Tiles',
    moduleKey: 'tricky_tiles',
    section: 'Classic Challenges',
    coverAsset: 'Tricky Tiles.png',
    description: 'Every new tile tries to land somewhere inconvenient.',
  }),
  makeDefinition({
    id: 'design-master-2',
    title: 'Design Master2',
    legacyName: 'Design Master2',
    moduleKey: 'design_master',
    section: 'Classic Challenges',
    coverAsset: 'Design Master2.png',
    description: 'A diagonal target pattern with strict spacing requirements.',
    hudSchema: ['patternText'],
    viewFlags: ['smallLabels'],
  }),
  makeDefinition({
    id: 'shape-shifter',
    title: 'Shape Shifter',
    legacyName: 'Shape Shifter',
    moduleKey: 'shape_shifter',
    section: 'Classic Challenges',
    coverAsset: 'Shape Shifter.png',
    description: 'The playable board shape changes from run to run.',
    shapeMode: 'dynamic',
    viewFlags: ['blockedMask'],
  }),
  makeDefinition({
    id: 'ferris-wheel',
    title: 'Ferris Wheel',
    legacyName: 'Ferris Wheel',
    moduleKey: 'ferris_wheel',
    section: 'Classic Challenges',
    coverAsset: 'Ferris Wheel.png',
    description: 'A rotating board twists your plans after each move.',
    hudSchema: ['remainingSteps'],
  }),
  makeDefinition({
    id: 'gravity-twist-2',
    title: 'Gravity Twist2',
    legacyName: 'Gravity Twist2',
    moduleKey: 'gravity_twist',
    section: 'Classic Challenges',
    coverAsset: 'Gravity Twist2.png',
    description: 'Gravity not only drops tiles, it can merge them too.',
  }),
  makeDefinition({
    id: 'design-master-3',
    title: 'Design Master3',
    legacyName: 'Design Master3',
    moduleKey: 'design_master',
    section: 'Extended Challenges',
    coverAsset: 'Design Master3.png',
    description: 'Sparse target anchors reward disciplined board control.',
    hudSchema: ['patternText'],
    viewFlags: ['smallLabels'],
  }),
  makeDefinition({
    id: 'mystery-merge-2',
    title: 'Mystery Merge2',
    legacyName: 'Mystery Merge2',
    moduleKey: 'mystery_merge',
    section: 'Extended Challenges',
    coverAsset: 'Mystery Merge2.png',
    description: 'Fresh tiles arrive hidden, and merges reveal only part of the truth.',
    viewFlags: ['hiddenMask', 'tileTextOverride'],
    hudSchema: ['actionButton'],
  }),
  makeDefinition({
    id: 'ice-age',
    title: 'Ice Age',
    legacyName: 'Ice Age',
    moduleKey: 'ice_age',
    section: 'Extended Challenges',
    coverAsset: 'Ice Age.png',
    description: 'Tiles freeze in place if they stand still for too long.',
    viewFlags: ['tileOverlays', 'coverSprites', 'tileStyleVariant'],
  }),
  makeDefinition({
    id: 'isolated-island',
    title: 'Isolated Island',
    legacyName: 'Isolated Island',
    moduleKey: 'isolated_island',
    section: 'Extended Challenges',
    coverAsset: 'Isolated Island.png',
    description: 'A fragmented board forces you to route merges around islands.',
    viewFlags: ['coverSprites', 'tileStyleVariant'],
  }),
  makeDefinition({
    id: 'design-master-4',
    title: 'Design Master4',
    legacyName: 'Design Master4',
    moduleKey: 'design_master',
    section: 'Extended Challenges',
    coverAsset: 'Design Master4.png',
    description: 'Fractional anchor weights create a demanding asymmetric target.',
    hudSchema: ['patternText'],
    viewFlags: ['smallLabels'],
  }),
  makeDefinition({
    id: 'endless-factorization',
    title: 'Endless Factorization',
    legacyName: 'Endless Factorization',
    moduleKey: 'endless_family',
    section: 'Endless Experiments',
    coverAsset: 'Endless Factorization.png',
    description: 'Endless mode with special factorization events and traps.',
    viewFlags: ['coverSprites', 'tileTextOverride', 'tileStyleVariant'],
  }),
  makeDefinition({
    id: 'endless-explosions',
    title: 'Endless Explosions',
    legacyName: 'Endless Explosions',
    moduleKey: 'endless_family',
    section: 'Endless Experiments',
    coverAsset: 'Endless Explosions.png',
    description: 'Explosive tiles punctuate an endless score attack.',
    viewFlags: ['coverSprites'],
  }),
  makeDefinition({
    id: 'endless-giftbox',
    title: 'Endless Giftbox',
    legacyName: 'Endless Giftbox',
    moduleKey: 'endless_family',
    section: 'Endless Experiments',
    coverAsset: 'Endless Giftbox.png',
    description: 'Special giftboxes keep the board unpredictable forever.',
    viewFlags: ['coverSprites'],
  }),
  makeDefinition({
    id: 'endless-hybrid',
    title: 'Endless Hybrid',
    legacyName: 'Endless Hybrid',
    moduleKey: 'endless_family',
    section: 'Endless Experiments',
    coverAsset: 'Endless Hybrid.png',
    description: 'A chaotic mash-up of the endless rule variants.',
    viewFlags: ['coverSprites', 'tileTextOverride', 'tileStyleVariant'],
  }),
  makeDefinition({
    id: 'endless-airraid',
    title: 'Endless AirRaid',
    legacyName: 'Endless AirRaid',
    moduleKey: 'endless_family',
    section: 'Endless Experiments',
    coverAsset: 'Endless AirRaid.png',
    description: 'Incoming strikes reshape the endless battlefield.',
    viewFlags: ['coverSprites', 'blockedMask'],
  }),
];

export const MINIGAME_BY_ID = Object.fromEntries(MINIGAME_REGISTRY.map((definition) => [definition.id, definition]));

export function buildMenuPayload(difficulty, summaries = {}, snapshotKey) {
  const sectionMap = new Map();
  for (const definition of MINIGAME_REGISTRY) {
    const summaryKey = typeof snapshotKey === 'function' ? snapshotKey(definition.id, difficulty) : `${definition.id}:${Number(difficulty) ? 1 : 0}`;
    const item = {
      id: definition.id,
      title: definition.title,
      description: definition.description,
      coverUrl: definition.coverUrl,
      difficultyAware: Boolean(definition.difficultyAware),
      supportsPowerups: Boolean(definition.supportsPowerups),
      implemented: Boolean(definition.implemented),
      summary: {
        bestScore: 0,
        highestTile: 0,
        highestExp: 0,
        trophy: 0,
        ...(summaries?.[summaryKey] || {}),
      },
    };
    if (!sectionMap.has(definition.section)) {
      sectionMap.set(definition.section, []);
    }
    sectionMap.get(definition.section).push(item);
  }
  return {
    difficulty: Number(difficulty) ? 1 : 0,
    sections: Array.from(sectionMap, ([title, items]) => ({ title, items })),
    currentGameId: '',
  };
}
