from collections.abc import Sequence
import enum
from typing import Annotated, Any

import numpy
from numpy.typing import NDArray


class SymmMode(enum.Enum):
    Identity = 0

    Full = 1

    Diagonal = 2

    Horizontal = 3

    Min33 = 4

    Min24 = 5

    Min34 = 6

    Min34Top = 7

class PatternSpec:
    def __init__(self) -> None: ...

    @property
    def name(self) -> str: ...

    @name.setter
    def name(self, arg: str, /) -> None: ...

    @property
    def pattern_masks(self) -> list[int]: ...

    @pattern_masks.setter
    def pattern_masks(self, arg: Sequence[int], /) -> None: ...

    @property
    def success_shifts(self) -> list[int]: ...

    @success_shifts.setter
    def success_shifts(self, arg: Sequence[int], /) -> None: ...

    @property
    def symm_mode(self) -> int: ...

    @symm_mode.setter
    def symm_mode(self, arg: int, /) -> None: ...

    @property
    def physical_transform(self) -> int: ...

    @physical_transform.setter
    def physical_transform(self, arg: int, /) -> None: ...

    @property
    def inverse_physical_transform(self) -> int: ...

    @inverse_physical_transform.setter
    def inverse_physical_transform(self, arg: int, /) -> None: ...

    @property
    def logical_pattern_signature(self) -> int: ...

    @logical_pattern_signature.setter
    def logical_pattern_signature(self, arg: int, /) -> None: ...

    @property
    def physical_pattern_signature(self) -> int: ...

    @physical_pattern_signature.setter
    def physical_pattern_signature(self, arg: int, /) -> None: ...

class RunOptions:
    def __init__(self) -> None: ...

    @property
    def target(self) -> int: ...

    @target.setter
    def target(self, arg: int, /) -> None: ...

    @property
    def steps(self) -> int: ...

    @steps.setter
    def steps(self, arg: int, /) -> None: ...

    @property
    def docheck_step(self) -> int: ...

    @docheck_step.setter
    def docheck_step(self, arg: int, /) -> None: ...

    @property
    def pathname(self) -> str: ...

    @pathname.setter
    def pathname(self, arg: str, /) -> None: ...

    @property
    def is_free(self) -> bool: ...

    @is_free.setter
    def is_free(self, arg: bool, /) -> None: ...

    @property
    def is_variant(self) -> bool: ...

    @is_variant.setter
    def is_variant(self, arg: bool, /) -> None: ...

    @property
    def spawn_rate4(self) -> float: ...

    @spawn_rate4.setter
    def spawn_rate4(self, arg: float, /) -> None: ...

    @property
    def success_rate_dtype(self) -> str: ...

    @success_rate_dtype.setter
    def success_rate_dtype(self, arg: str, /) -> None: ...

    @property
    def deletion_threshold(self) -> float: ...

    @deletion_threshold.setter
    def deletion_threshold(self, arg: float, /) -> None: ...

    @property
    def relative_deletion_threshold(self) -> float: ...

    @relative_deletion_threshold.setter
    def relative_deletion_threshold(self, arg: float, /) -> None: ...

    @property
    def deletion_threshold_signal_path(self) -> str: ...

    @deletion_threshold_signal_path.setter
    def deletion_threshold_signal_path(self, arg: str, /) -> None: ...

    @property
    def compress(self) -> bool: ...

    @compress.setter
    def compress(self, arg: bool, /) -> None: ...

    @property
    def compress_temp_files(self) -> bool: ...

    @compress_temp_files.setter
    def compress_temp_files(self, arg: bool, /) -> None: ...

    @property
    def optimal_branch_only(self) -> bool: ...

    @optimal_branch_only.setter
    def optimal_branch_only(self, arg: bool, /) -> None: ...

    @property
    def chunked_solve(self) -> bool: ...

    @chunked_solve.setter
    def chunked_solve(self, arg: bool, /) -> None: ...

    @property
    def num_threads(self) -> int: ...

    @num_threads.setter
    def num_threads(self, arg: int, /) -> None: ...

class AdvancedPatternSpec:
    def __init__(self) -> None: ...

    @property
    def name(self) -> str: ...

    @name.setter
    def name(self, arg: str, /) -> None: ...

    @property
    def pattern_masks(self) -> list[int]: ...

    @pattern_masks.setter
    def pattern_masks(self, arg: Sequence[int], /) -> None: ...

    @property
    def success_shifts(self) -> list[int]: ...

    @success_shifts.setter
    def success_shifts(self, arg: Sequence[int], /) -> None: ...

    @property
    def symm_mode(self) -> int: ...

    @symm_mode.setter
    def symm_mode(self, arg: int, /) -> None: ...

    @property
    def physical_transform(self) -> int: ...

    @physical_transform.setter
    def physical_transform(self, arg: int, /) -> None: ...

    @property
    def inverse_physical_transform(self) -> int: ...

    @inverse_physical_transform.setter
    def inverse_physical_transform(self, arg: int, /) -> None: ...

    @property
    def logical_pattern_signature(self) -> int: ...

    @logical_pattern_signature.setter
    def logical_pattern_signature(self, arg: int, /) -> None: ...

    @property
    def physical_pattern_signature(self) -> int: ...

    @physical_pattern_signature.setter
    def physical_pattern_signature(self, arg: int, /) -> None: ...

    @property
    def num_free_32k(self) -> int: ...

    @num_free_32k.setter
    def num_free_32k(self, arg: int, /) -> None: ...

    @property
    def fixed_32k_shifts(self) -> list[int]: ...

    @fixed_32k_shifts.setter
    def fixed_32k_shifts(self, arg: Sequence[int], /) -> None: ...

    @property
    def small_tile_sum_limit(self) -> int: ...

    @small_tile_sum_limit.setter
    def small_tile_sum_limit(self, arg: int, /) -> None: ...

    @property
    def target(self) -> int: ...

    @target.setter
    def target(self, arg: int, /) -> None: ...

class ClassicBookReader:
    def __init__(self, pattern_spec: PatternSpec, is_variant: bool = False) -> None: ...

    def move_on_dic(self, board: Sequence[Sequence[int]], path_list: Sequence[tuple[str, str]], pattern_full: str, nums_adjust: int) -> tuple[dict[str, float | str | None], str]: ...

    def get_random_state(self, path_list: Sequence[tuple[str, str]], pattern_full: str, spawn_rate4: float) -> int: ...

class AdvancedBookReader:
    def __init__(self, pattern_spec: AdvancedPatternSpec, is_variant: bool = False) -> None: ...

    def move_on_dic(self, board: Sequence[Sequence[int]], path_list: Sequence[tuple[str, str]], pattern_full: str, nums_adjust: int) -> tuple[dict[str, float | str | None], str]: ...

    def get_random_state(self, path_list: Sequence[tuple[str, str]], pattern_full: str, spawn_rate4: float) -> int: ...

class EXBookReader:
    def __init__(self, pattern_spec: PatternSpec, is_variant: bool = False) -> None: ...

    def move_on_dic(self, board: Sequence[Sequence[int]], path_list: Sequence[tuple[str, str]], pattern_full: str, nums_adjust: int) -> tuple[dict[str, float | str | None], str]: ...

    def get_random_state(self, path_list: Sequence[tuple[str, str]], pattern_full: str, spawn_rate4: float) -> int: ...

class PatternLayer:
    def __init__(self) -> None: ...

    @property
    def size(self) -> int: ...

    @property
    def empty(self) -> bool: ...

    @property
    def dtype_name(self) -> str: ...

def get_build_progress() -> tuple[int, int]: ...

def reset_build_progress(total: int = 0) -> None: ...

def trie_compress_book(book_path: str, success_rate_dtype: str = "uint32") -> bool: ...

def trie_decompress_search(path_prefix: str, board: int, success_rate_dtype: str) -> float: ...

def find_classic_value(pathname: str, filename: str, search_key: int, success_rate_dtype: str = "uint32") -> float | None: ...

def apply_sym_like(board: int, symm_index: int) -> int: ...

def lookup_ex_zbook_cold(zbook_path: str, zlut_path: str, board: int) -> dict[str, Any]: ...

def run_pattern_generate(arr_init: Annotated[NDArray[numpy.uint64], dict(shape=(None,), order='C', device='cpu', writable=False)], pattern_spec: PatternSpec, run_options: RunOptions) -> tuple[bool, PatternLayer, PatternLayer]: ...

def run_pattern_solve(d1: PatternLayer, d2: PatternLayer, pattern_spec: PatternSpec, run_options: RunOptions) -> None: ...

def run_pattern_build(arr_init: Annotated[NDArray[numpy.uint64], dict(shape=(None,), order='C', device='cpu', writable=False)], pattern_spec: PatternSpec, run_options: RunOptions) -> None: ...

def run_pattern_build_ad(arr_init: Annotated[NDArray[numpy.uint64], dict(shape=(None,), order='C', device='cpu', writable=False)], pattern_spec: AdvancedPatternSpec, run_options: RunOptions) -> None: ...

def run_pattern_build_zmask(arr_init: Annotated[NDArray[numpy.uint64], dict(shape=(None,), order='C', device='cpu', writable=False)], pattern_spec: PatternSpec, run_options: RunOptions) -> None: ...

def run_pattern_solve_zmask(arr_init: Annotated[NDArray[numpy.uint64], dict(shape=(None,), order='C', device='cpu', writable=False)], pattern_spec: PatternSpec, run_options: RunOptions) -> None: ...

def run_pattern_solve_zmask_single_layer(arr_init: Annotated[NDArray[numpy.uint64], dict(shape=(None,), order='C', device='cpu', writable=False)], pattern_spec: PatternSpec, run_options: RunOptions, step: int) -> None: ...

def compress_ex_zbook_result(zbook_path: str, zlut_path: str, output_path: str, bucket_block_buckets: int = 4096, success_block_values: int = 65536, compression_level: int = 5) -> dict[str, Any]: ...

def lookup_ex_zbook_result_cold(compressed_path: str, zlut_path: str, board: int) -> dict[str, Any]: ...

def sample_bc_compressed_random_state(compressed_path: str, target_rank: int = 8, spawn_rate4: float = 0.1) -> int: ...
