

def find_best_egtb_move(board: int, table_type: int) -> list[float]: ...

def resolve_32768_doubles(board: int) -> int: ...

class AIPlayer:
    def __init__(self, arg: int, /) -> None: ...

    def reset_board(self, new_board: int) -> None: ...

    def clear_cache(self) -> None: ...

    def update_spawn_rate(self, new_rate: float) -> None: ...

    def evaluate(self, board: int) -> int: ...

    def start_search(self, depth: int = 3) -> None: ...

    @property
    def max_d(self) -> int: ...

    @max_d.setter
    def max_d(self, arg: int, /) -> None: ...

    @property
    def best_operation(self) -> int: ...

    @best_operation.setter
    def best_operation(self, arg: int, /) -> None: ...

    @property
    def board(self) -> int: ...

    @board.setter
    def board(self, arg: int, /) -> None: ...

    @property
    def max_threads(self) -> int: ...

    @max_threads.setter
    def max_threads(self, arg: int, /) -> None: ...

    @property
    def do_check(self) -> int: ...

    @do_check.setter
    def do_check(self, arg: int, /) -> None: ...

    @property
    def spawn_rate4(self) -> float: ...

    @spawn_rate4.setter
    def spawn_rate4(self, arg: float, /) -> None: ...

    @property
    def prune(self) -> int: ...

    @prune.setter
    def prune(self, arg: int, /) -> None: ...

    @property
    def masked_count(self) -> int: ...

    @property
    def fixed_mask(self) -> int: ...

    @property
    def dead_score(self) -> int: ...

    @property
    def scores(self) -> tuple[int, int, int, int]: ...

    @property
    def node(self) -> int: ...

    @property
    def stop_search(self) -> bool: ...

    @stop_search.setter
    def stop_search(self, arg: bool, /) -> None: ...

class EvilGen:
    def __init__(self, initial_board: int) -> None: ...

    def reset_board(self, new_board: int) -> None: ...

    def start_search(self, depth: int = 4) -> None: ...

    def dispatcher(self, board: int) -> int: ...

    def gen_new_num(self, depth: int = 4) -> tuple[int, int, int]: ...

    @property
    def max_d(self) -> int: ...

    @max_d.setter
    def max_d(self, arg: int, /) -> None: ...

    @property
    def hardest_pos(self) -> int: ...

    @hardest_pos.setter
    def hardest_pos(self, arg: int, /) -> None: ...

    @property
    def hardest_num(self) -> int: ...

    @hardest_num.setter
    def hardest_num(self, arg: int, /) -> None: ...

    @property
    def board(self) -> int: ...

    @board.setter
    def board(self, arg: int, /) -> None: ...

    @property
    def node(self) -> int: ...
