from __future__ import annotations
import typing
__all__: list[str] = ['AIPlayer', 'EvilGen', 'find_best_egtb_move']
class AIPlayer:
    stop_search: bool
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def clear_cache(self) -> None:
        ...
    def reset_board(self, new_board: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def start_search(self, depth: typing.SupportsInt | typing.SupportsIndex = 3) -> None:
        ...
    @property
    def best_operation(self) -> int:
        ...
    @best_operation.setter
    def best_operation(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def board(self) -> int:
        ...
    @board.setter
    def board(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def do_check(self) -> int:
        ...
    @do_check.setter
    def do_check(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def max_d(self) -> int:
        ...
    @max_d.setter
    def max_d(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def max_threads(self) -> int:
        ...
    @max_threads.setter
    def max_threads(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def node(self) -> int:
        ...
    @property
    def prune(self) -> int:
        ...
    @prune.setter
    def prune(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def scores(self) -> list[int]:
        ...
    @property
    def spawn_rate4(self) -> float:
        ...
    @spawn_rate4.setter
    def spawn_rate4(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
class EvilGen:
    def __init__(self, initial_board: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def dispatcher(self, board: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def gen_new_num(self, depth: typing.SupportsInt | typing.SupportsIndex = 4) -> tuple[int, int, int]:
        ...
    def reset_board(self, new_board: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def start_search(self, depth: typing.SupportsInt | typing.SupportsIndex = 4) -> None:
        ...
    @property
    def board(self) -> int:
        ...
    @board.setter
    def board(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def hardest_num(self) -> int:
        ...
    @hardest_num.setter
    def hardest_num(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def hardest_pos(self) -> int:
        ...
    @hardest_pos.setter
    def hardest_pos(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def max_d(self) -> int:
        ...
    @max_d.setter
    def max_d(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def node(self) -> int:
        ...
def find_best_egtb_move(board: typing.SupportsInt | typing.SupportsIndex, table_type: typing.SupportsInt | typing.SupportsIndex) -> tuple[int, float]:
    ...
