<script setup>
import { computed, ref, watch } from 'vue';
const props=defineProps({workflow:Object,projects:{type:Array,default:()=>[]},phase:String,token:String,lang:{type:String,default:'zh'},canSubmit:Boolean,canBlind:Boolean,busy:Boolean,seconds:Number,blindSubmitted:Boolean,nameOf:Function,iconOf:Function});
const emit=defineEmits(['submit','blind']);
const picks=ref([]),bans=ref([]),blind=ref('');
const txt=(zh,en)=>props.lang==='zh'?zh:en;
const name=key=>props.nameOf?.(key)||props.projects.find(p=>p.key===key)?.name||key;
const side=value=>value==='yellow'?txt('黄方','Yellow'):value==='white'?txt('白方','White'):txt('抽签','Draw');
const step=computed(()=>props.workflow?.current_step);
const excluded=computed(()=>new Set([...(props.workflow?.selected||[]),...(props.workflow?.banned||[])]));
const valid=computed(()=>step.value && picks.value.length===step.value.picks && bans.value.length===step.value.bans);
watch(()=>props.token,()=>{picks.value=[];bans.value=[];blind.value='';});
function toggle(key,type){const list=type==='picks'?picks:bans, other=type==='picks'?bans:picks; if(list.value.includes(key)){list.value=list.value.filter(k=>k!==key);return;}if(list.value.length>=step.value[type])return;other.value=other.value.filter(k=>k!==key);list.value.push(key);}
const mark=key=>{const i=props.workflow.selected.indexOf(key);return i>=0?String.fromCharCode(65+i):props.workflow.banned.includes(key)?'BAN':'';};
</script>
<template>
  <section class="workflow">
    <header><div><small>{{ txt('项目选禁','PROJECT DRAFT') }}</small><h2>{{ workflow.complete?txt('BP 已完成','Draft complete'):phase==='BLIND_PICK'?txt('双方盲选','Simultaneous blind picks'):side(workflow.active_side) }}</h2></div><strong v-if="seconds!=null && !workflow.complete" class="countdown">{{ seconds }}s</strong></header>
    <ol class="workflow-steps"><li v-for="(s,i) in workflow.steps" :key="i" :class="{current:i===workflow.step_index && phase==='DRAFT_STEP',done:i<workflow.step_index}"><span>{{ i+1 }} · {{ s.actor==='first'?txt('先手','First'):txt('后手','Second') }}</span><b>{{ s.bans?`B${s.bans} `:'' }}{{ s.picks?`P${s.picks}`:'' }}</b></li><li :class="{current:phase==='BLIND_PICK',done:workflow.complete}"><span>{{ txt('最终抽签','Final draw') }}</span><b>P1</b></li></ol>
    <p v-if="step">{{ txt(`本步选择 ${step.picks} 项，禁用 ${step.bans} 项。`,`This step: pick ${step.picks}, ban ${step.bans}.`) }} {{ canSubmit?txt('按选择的先后顺序安排对局。','Games follow your pick order.'):txt('等待该方队长提交。','Waiting for the captain.') }}</p>
    <p v-if="phase==='BLIND_PICK'">{{ blindSubmitted?txt('本方已密封提交，等待另一方。','Your pick is sealed; waiting for the other side.'):txt('双方选择互不可见，可选择同一项目；提交后抽签。','Picks are hidden from the opponent and may match. A draw follows both submissions.') }}</p>
    <div v-if="canSubmit && !workflow.complete" class="selection-order"><span>PICK {{ picks.map((k,i)=>`${i+1}. ${name(k)}`).join(' → ') || '—' }}</span><span>BAN {{ bans.map(name).join(' · ') || '—' }}</span></div>
    <div class="workflow-pool"><article v-for="p in projects" :key="p.key" :class="{excluded:excluded.has(p.key),picked:picks.includes(p.key),banned:bans.includes(p.key),blind:blind===p.key}"><img v-if="iconOf?.(p.key)" :src="iconOf(p.key)" alt=""/><div><b>{{ name(p.key) }}</b><small>{{ mark(p.key) || (picks.includes(p.key)?`P${picks.indexOf(p.key)+1}`:bans.includes(p.key)?'BAN':'') }}</small></div><div v-if="!excluded.has(p.key)" class="project-actions"><template v-if="canSubmit && step"><button v-if="step.picks" type="button" :aria-pressed="picks.includes(p.key)" :disabled="busy||(!picks.includes(p.key)&&picks.length>=step.picks)" @click="toggle(p.key,'picks')">PICK</button><button v-if="step.bans" type="button" :aria-pressed="bans.includes(p.key)" :disabled="busy||(!bans.includes(p.key)&&bans.length>=step.bans)" @click="toggle(p.key,'bans')">BAN</button></template><button v-if="canBlind" type="button" :aria-pressed="blind===p.key" :disabled="busy" @click="blind=p.key">{{ txt('盲选','Blind pick') }}</button></div></article></div>
    <button v-if="canSubmit && step" class="submit" type="button" :disabled="busy||!valid" @click="emit('submit',{picks:[...picks],bans:[...bans]})">{{ txt('确认本步选禁','Confirm step') }}</button>
    <button v-if="canBlind" class="submit" type="button" :disabled="busy||!blind" @click="emit('blind',blind)">{{ txt('密封提交盲选','Submit sealed pick') }}</button>
    <ol class="workflow-history"><li v-for="(h,i) in workflow.history" :key="i"><b>{{ side(h.side) }}</b><span v-if="h.picks.length">PICK · {{ h.picks.map(name).join(' → ') }}</span><span v-if="h.bans.length">BAN · {{ h.bans.map(name).join(' · ') }}</span><small v-if="h.automatic">{{ txt('系统','Automatic') }}</small></li></ol>
  </section>
</template>
<style scoped>
.workflow{--wf-border:var(--competition-border,var(--match-line,#334155));--wf-card:var(--competition-card,var(--match-card,#17243a));--wf-accent:var(--competition-accent,var(--match-accent,#d8bd69));min-width:0;display:grid;gap:16px;padding:20px;background:var(--wf-card);border:1px solid var(--wf-border);border-radius:10px;color:inherit}.workflow header{display:flex;justify-content:space-between;align-items:center}.workflow header small{color:var(--wf-accent);letter-spacing:.12em}.workflow h2{margin:6px 0;font-size:22px}.workflow p{margin:0;line-height:1.6}.countdown{font-size:24px;font-variant-numeric:tabular-nums}.workflow-steps{display:flex;flex-wrap:wrap;gap:8px;list-style:none;padding:0;margin:0}.workflow-steps li{display:grid;gap:5px;border:1px solid var(--wf-border);padding:9px 12px;border-radius:6px;font-size:13px}.workflow-steps .current{border-color:var(--wf-accent);color:var(--wf-accent)}.workflow-steps .done{opacity:.6}.workflow-pool{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:10px}.workflow-pool article{border:1px solid var(--wf-border);padding:12px;display:flex;align-items:center;gap:10px;flex-wrap:wrap;border-radius:7px}.workflow-pool img{width:40px;height:40px;border-radius:5px}.workflow-pool article>div:not(.project-actions){flex:1;min-width:0;display:grid;gap:4px}.workflow-pool b{font-size:14px;overflow-wrap:anywhere}.workflow-pool small{color:var(--wf-accent)}.workflow-pool .excluded{opacity:.5}.workflow-pool .picked,.workflow-pool .blind{border-color:var(--wf-accent)}.workflow-pool .banned{border-color:#c57164}.project-actions{width:100%;display:flex;gap:8px}.workflow button{font:inherit;color:inherit;border:1px solid var(--wf-border);background:transparent;border-radius:5px;padding:8px 12px;cursor:pointer}.workflow button[aria-pressed=true],.workflow .submit{background:var(--wf-accent);color:var(--competition-page,var(--match-bg,#111c30))}.workflow button:disabled{opacity:.4;cursor:default}.selection-order{display:grid;gap:8px;font-size:14px}.workflow-history{padding:0;list-style:none;margin:0;display:grid;gap:8px;font-size:13px}.workflow-history li{display:flex;flex-wrap:wrap;gap:12px;padding-top:10px;border-top:1px solid var(--wf-border)}.workflow-history small{opacity:.6}@media(max-width:500px){.workflow{padding:12px}.workflow-pool{grid-template-columns:repeat(2,minmax(0,1fr))}.workflow-pool article{padding:8px}.project-actions{flex-wrap:wrap}}
</style>
